name: Haskell CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
          ghc-version: ['9.6.1']
          cabal-version: ['3.10']
          project: [practica1, practica2, practica3, practica4]
          exclude:
            - project: practica4
        fail-fast: false # If one fails all others will cancel
      
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc-version }}
        cabal-version: ${{ matrix.cabal-version }}

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    
    - name: Build
      run: cd ${{ matrix.project }} && cabal build --enable-tests --enable-benchmarks all
    
    - name: Run runtests
      run: cd ${{ matrix.project }} && cabal run runtests
    
    - name: Run tests
      run: cd ${{ matrix.project }} && cabal test all
      continue-on-error: true
